.DEFAULT_GOAL := help

help: ## Autogenerated help reference for make
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
.PHONY: help

clean: ## Clean build directory
	./gradlew clean

test: ## Run tests
	./gradlew test

build: ## Build the executable jar for this project. Tests won't be run.
	./gradlew build -x test

deploy-rest-api: build ## Deploy the REST API application in production mode (on port 8080)
	nohup java -jar \
		-Dspring.profiles.active=production \
		-Xmx2048m \
		rest-api/build/libs/rest-api.jar \
		&

deploy-telegram-bot: build ## Run telegram bot in production mode
	nohup java -jar \
		-Dspring.profiles.active=production \
		-Xmx1024m \
		telegram-bot/build/libs/telegram-bot.jar \
		&
	@make pid MODULE=telegram-bot

logs: ## See logs of running application
	@tail -f nohup.out -n 20

MODULE ?= "rest-api"
pid: ## Find PID of running application for kill
	@ps aux \
		| grep $(MODULE) \
		| grep jar \
		| grep java \
		| grep -v grep \
		|| echo "Application is not running"

.PHONY: all $(MAKECMDGOALS)
