.DEFAULT_GOAL := help

help: ## Autogenerated help reference for make
	@grep -E '^[a-zA-Z_-]+:.*?## .*$$' $(MAKEFILE_LIST) | sort | awk 'BEGIN {FS = ":.*?## "}; {printf "\033[36m%-30s\033[0m %s\n", $$1, $$2}'
.PHONY: help

clean: ## Clean build directory
	./gradlew clean

test: ## Run tests
	./gradlew test

build: ## Build the executable jar for this project. Tests won't be run.
	./gradlew build -DskipTests

deploy: build ## Deploy the application in production mode (on port 8080)
	nohup java -jar \
		-Dspring.profiles.active=production \
		-Xmx2048m \
		rest-api/target/rest-api-0.1.jar \
		&

logs: ## See logs of running application
	@tail -f nohup.out -n 20

pid: ## Find PID of running application for kill
	@ps aux \
		| grep rest-api \
		| grep jar \
		| grep java \
		| grep -v grep \
		|| echo "Application is not running"

