version: '3'

services:
  elasticsearch:
    image: elasticsearch:7.10.1
    environment:
      #- cluster.name=docker-cluster
      - bootstrap.memory_lock=true
      - transport.host=127.0.0.1
      - http.host=0.0.0.0
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    ulimits:
      memlock:
        soft: -1
        hard: -1
    ports:
      - "9200:9200"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch
    networks: 
      - elastic
  kibana:
    image: kibana:7.10.1
    ports:
      - "5601:5601"
    networks: 
      - elastic
    depends_on:
      - elasticsearch

volumes:
  elasticsearch_data:
    driver: local

networks:
  elastic:
    driver: bridge
